### PR TITLE
Review tiles are dynamically rendering from API

### PR DESCRIPTION
**Pull request by aaronfife**
- added CSS styling to make the RnR widget more inline with the app
- built out the review widget to dynamically render the API data

current: 
Screen Shot 2021-09-14 at 12 09 50 PM

### CODE REVIEW

**Review by ashequl93 — APPROVED** [review]

**Review by Jhaines1988 — CHANGES_REQUESTED** [review]
Hey Aaron,  

This looks very good to me,  But I have one request that may seem trivial but I think its important. 

You are still pushing your  bundle.js to github , and you are also pushing the coverage files which we agreed to not include in our commits. 

please run git rm --cached client/dist/bundle.js in  in your reviewComponent2 branch 

also run 

git rm --cached coverage -r



 if you wouldn't mind, please  run these commands and commit and push  these changes after you ensure your  bundle and coverage files are actually being ignored. Other than that  everything looks great

**Comment by aaronfife** [comment]
@Jhaines1988 - thank you for your catch. i have ran the commands you recommended.

**Review by Jhaines1988 — APPROVED** [review]
Thanks Aaron!    I wish I had your CSS skills. We'll definitely have to collaborate on the final structure and I think you might be a good person to lead that process. We can bring it up in the coming standups/ meetings , if you'd like. 

( by lead I don't mean it would be your sole responsibility, just to clarify)

**Review by AndrewJuniorB — APPROVED** [review]
Yeah a lot css and Aaron is very good in this. Just question, how are using starAndMonthTile object ?

**Pull request merged**
