### PR TITLE
Ratings & Reviews (RnR) Component

### PR DESCRIPTION
**Pull request by aaronfife**
Hey guys, lots of code here as well. I wanted to get the skeleton of my components built before i started inputing data from the API. Everything on here so far is static, I have not implemented any dynamic code as of yet.

- built out my main 3 components
- created 2 semi-lame tests with jest
- added styling with CSS
  - trying to keep my ID and ClassNames fairly intuitive, let me know your thoughts

Here is how it is looking so far:
Screen Shot 2021-09-11 at 4 53 52 PM

### CODE REVIEW

**Review by ashequl93 — CHANGES_REQUESTED** [review]
Hi @aaronfife , very clean work. 👍  I could not find anything for you to change other than the conflicting files. Can you resolve those 3 files? Also, your App.jsx file looks very new. But it should have code from Joe and my work. Can you verify what's going on? 
Screen Shot 2021-09-13 at 7 32 47 PM

**Comment by AndrewJuniorB** [comment]
Looks good for me. Don`t see any changes needed besides conflicts which Ash mentioned before.

**Comment by aaronfife** [comment]
@AndrewJuniorB @ashequl93 
Thanks for your responses. I believe i have fixed the merge conflicts now.

@ashequl93 
the app.jsx file is now up to date and please dont forget to open the hidden code on the side ;)

**Review by ashequl93 — APPROVED** [review]
Looks good to me.

**Review by Jhaines1988 — APPROVED** [review]
This looks good to me, but see the comment I left on Andrews commit as well. 

We all have been caching  bundle.js. Therefore, adding it to git ignore at this point wont do anything. 

First you have to run 
git rm --cached client/dist/bundle.js 

Then, you can add it to git ignore and it will actually be ignored.

**Review by AndrewJuniorB — APPROVED** [review]

**Pull request merged**
